### ISSUE TITLE
RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by CharlieBrownCharacter** [Gugustinette/Nuxt-Leaflet#9]
I have a Nuxt3 application running just fine. Now, whenever I build my project to be able to deploy it I get the following error:

```
 ERROR  RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)                                                                                                                           nitro 5:31:59 PM


1: �PNG
   ^
2:
IHDR�����IDATx�W�cY�څ����i�k�޶L�
                                �c�5��dm��x�����f���U�^���=�<'���2��v��nX�0
                                                                           E�
...                                                                          ��h��v*


 ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)                                                                                                                                              5:31:59 PM

  at error (node_modules/rollup/dist/es/shared/parseAst.js:337:30)
  at parseError (node_modules/rollup/dist/es/shared/parseAst.js:972:9)
  at convertNode (node_modules/rollup/dist/es/shared/parseAst.js:2057:12)
  at convertProgram (node_modules/rollup/dist/es/shared/parseAst.js:965:12)
  at parseAstAsync (node_modules/rollup/dist/es/shared/parseAst.js:2108:12)
  at async Module.tryParseAsync (node_modules/rollup/dist/es/shared/node-entry.js:13539:20)
  at async Module.setSource (node_modules/rollup/dist/es/shared/node-entry.js:13120:35)
  at async ModuleLoader.addModuleSource (node_modules/rollup/dist/es/shared/node-entry.js:17810:13)



 ERROR  Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
```

I have searched the following questions in QA:

 - https://stackoverflow.com/questions/72921915/unexpected-character-note-that-you-need-plugins-to-import-files-that-are-no
 - https://stackoverflow.com/questions/63911896/error-unexpected-character-note-that-you-need-plugins-to-import-files-that
 - https://stackoverflow.com/questions/72027309/rollup-build-scss-error-tip-error-unexpected-character-note-that-you-need
 - https://stackoverflow.com/questions/70629740/vue-js-vite-build-error-with-videosource-tags

All of these questions are related to SCSS and neither of them actually shows anything related to my `png`.

Currently I'm only importing a single image into my project in my `app.vue`:

```
<NuxtImg
 class="w-full fixed top-0 z-[-1]"
 src="/images/dark-bg.png"
/>
```

In my `public/` folder I simply have the following structure:

```
- images
-- dark-bg.png
- favicon.ico

```

I have tried removing completely this `dark-bg.png` from my project alongside the `<NuxtImg>` tag but the error still persists.

Here's my `nuxt.config.ts`:

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
// @ts-ignore
import type { NuxtPage } from "@nuxt/schema";

// @ts-ignore
export default defineNuxtConfig({
  nitro: {
    prerender: {
      autoSubfolderIndex: false
    },
  },
  devtools: { enabled: false },
  hooks: {
    'pages:extend'(pages: NuxtPage[]) {
      pages.push({
        name: 'location',
        path: '/location/:citySlug',
        file: '~/pages/spots/[citySlug].vue'
      })
    }
  },
  runtimeConfig: {
    public: {
      baseURL: process.env.NUXT_API_BASE_URL || 'https://api.sunsetzinho.com/'
    }
  },
  modules: [
    'nuxt-primevue',
    'nuxt3-leaflet',
    'nuxt-icon',
    '@pinia/nuxt',
    '@vee-validate/nuxt',
    '@nuxt/image',
    '@nuxtjs/tailwindcss'
  ],
  primevue: {},
  veeValidate: {
    // disable or enable auto imports
    autoImports: true,
    // Use different names for components
    componentNames: {
      Form: 'VeeForm',
      Field: 'VeeField',
      FieldArray: 'VeeFieldArray',
      ErrorMessage: 'VeeErrorMessage'
    }
  },
  css: [
    'primevue/resources/themes/aura-dark-noir/theme.css',
    '~/assets/css/main.css',
    '~/assets/css/vendors/leaflet.css'
  ]
})

```

Here's my `package.json`:

```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^6.11.3",
    "@types/lodash.debounce": "^4.0.9",
    "@types/platform": "^1.3.6",
    "autoprefixer": "^10.4.17",
    "nuxt": "^3.10.0",
    "nuxt-icon": "^0.6.8",
    "nuxt-primevue": "^0.2.2",
    "nuxt3-leaflet": "^1.0.12",
    "prettier": "3.2.5",
    "vue": "^3.4.15",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxt/image": "^1.3.0",
    "@pinia/nuxt": "^0.5.1",
    "@tiptap/pm": "^2.2.2",
    "@tiptap/starter-kit": "^2.2.2",
    "@tiptap/vue-3": "^2.2.2",
    "@vee-validate/nuxt": "^4.12.5",
    "date-fns": "^3.3.1",
    "lodash.debounce": "^4.0.8",
    "mitt": "^3.0.1",
    "pinia": "^2.1.7",
    "platform": "^1.3.6",
    "primevue": "^3.47.2",
    "yup": "^1.3.3"
  }
}

```

I have the following `png` files in my `node_modules`:

```
$ find node_modules -type f -regex ".*\.png"
node_modules/undici/docs/assets/lifecycle-diagram.png
node_modules/leaflet/dist/images/layers.png
node_modules/leaflet/dist/images/marker-icon.png
node_modules/leaflet/dist/images/marker-icon-2x.png
node_modules/leaflet/dist/images/marker-shadow.png
node_modules/leaflet/dist/images/layers-2x.png
```

It looks like the following file is giving problems `node_modules/leaflet/dist/images/marker-shadow.png`:

```
$ cat node_modules/leaflet/dist/images/marker-shadow.png
�PNG

IHDR)i�}1IDATx�҅��@�
s�Ҕ������p�T۝~��N��ܐ7d������
                            ~�_���"cP\�
�W��Aq�4�^	�W�$Aq�C�Q�_�R�Cfd7&�d՚�H͞_i�8�H�n���I���0bG�i(#T!�F1�	2�o�D$G��)��ɸ��*���	/��etԀZ�P��Hu�����e��Q�
                                                                                                                       �-�ʘ"��~���aK,�Y��vG%���
                                                                                                                                                ��Q������t���
                                                                                                                                                             +˜Sd+^�Q�/0&�����MM�<�8���
��c�.� u$G��I�q�}��i�D\ȷ�Dt�~�@���jKe��W�zRB�p�8�|�\Ŕ�$�zR��%)�C9���fR(                                                                                                                ��k̸�$��M
�W@���],WK!����~�Rt��r�H�A˄���P�À�a{�Adٱ�+(
                                            R�g��Z��dG" \��4��b�'|�|&y$�):0"
                                                                            �q!�P�;>�彁_ِ3����L5N��
�h���c�Ƨ��ġaM^�q����#R�t�_�3�8�@bIEND�B`�%
```

I'm not really 100% sure the problem is with this library but from what it looks like the file giving issues are one of the `png` in `node_modules/leaflet/dist/images/` folder. Would you giving me a light what next step I could do to fix this issue?

**Comment by CharlieBrownCharacter** [comment]
I just removed this package from my project and it is compiling correctly. I will keep updating my findings here

**Comment by Gugustinette** [comment]
So adding `nuxt3-leaflet` to your project causes this error ?
Really weird behavior.

You're not even using the package ? (Like adding a map somewhere in your code)

**Comment by CharlieBrownCharacter** [comment]
Installing it and adding to `nuxt.config.ts` doesn't seem to break anything. Things work just fine:

```
// https://nuxt.com/docs/api/configuration/nuxt-config
// @ts-ignore
import type { NuxtPage } from "@nuxt/schema";

// @ts-ignore
export default defineNuxtConfig({
  modules: [
    // ...
    'nuxt3-leaflet',
  ],
})

```

I'm currently using the version `v1.0.2`. I will keep upgrading it in chunks and see if anything breaks.

Now, I have tried to simply just import the types in my Vue setup function and it works just fine:

```
<script setup lang="ts">
import type { LeafletMouseEvent, LatLng, LatLngBounds } from 'leaflet'
import type { LMap } from '@vue-leaflet/vue-leaflet'
</script>
```

Now, simply adding a map to the application it breaks it with the error provided above:

```vue
<template>
  <LMap
    :options="{ zoomControl: false }"
    :ref="map"
    :zoom="zoom"
    :center="mapCenter"
    :min-zoom="13"
    :max-zoom="18"
    @update:center="onUpdateCenter"
    @update:zoom="onZoomUpdate"
    @update:bounds="onUpdateBounds"
    @click="onMapClick"
    @ready="onMapReady"
  >
  </LMap>
</template>
```

I have also tried to remove any listeners that involves importing anything that uses any types from the `leaflet` library but it still broke only when I add a map.

For example, if I do:

```
<template>
  <div>a map should be here</div>
</template>

<script setup lang="ts">
import type { LeafletMouseEvent, LatLng, LatLngBounds } from 'leaflet'
</script>
```


it breaks with the error above whe trying to build the project.

**Comment by CharlieBrownCharacter** [comment]
I have fixed the issue by wrapping `LMap` into a `client-only`:

```vue
<client-only>
  <LMap ...> </LMap>
</client-only>
```

**Comment by Gugustinette** [comment]
Yeah there are some issues with server features, as the plugin cannot be used on server-side (as it is a client library lol).

I'll take note of this behavior when writing the official documentation 👌

**Comment by CharlieBrownCharacter** [comment]
@Gugustinette I thought the component was taking care of that already. That's why it never went through my mind to wrap it in `client-only`.

Thank you. I appreciate the help.

**Comment by Gugustinette** [comment]
Yeah I remember trying to make the component Client Only here : https://github.com/Gugustinette/Nuxt-Leaflet/blob/b378cfb4bb7d2f82d26782ed8b68651ec63e078f/src/module.ts#L59

But it literally through errors so I made it available on server-side. Clearly something to improve !
